### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by Ansontheprogrammer** [nikkilr88/ui-blocks#1]
Hey I've been trying to clone the repo to run the example directories package.json. Every time I run yarn start I receive this error, with index.js
`ReactDOM.render(<App />, document.getElementById('root'))`
"Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem."

**Comment by nikkilr88** [comment]
That's odd! I can't replicate the build error.

**Comment by mtliendo** [comment]
Same issue.

It's because the project already has `react` and `react-dom` declared in its [main package.json](https://github.com/nikkilr88/ui-blocks/blob/master/package.json#L26-L27)

Easy enough to fix, `react` and `react-dom` would need to be listed as `peer-dependencies` instead. I attached a screenshot below to show how the `example/package.json` file should be changed.

Not sure if @nikkilr88 would want a PR for the change, or if it it could be squeezed in as part of #2 

![image](https://user-images.githubusercontent.com/5106417/77240783-eac22280-6bb7-11ea-983d-45a7d8a79ff0.png)

ps) super nice library btw 💯

**Comment by nikkilr88** [comment]
> Same issue.
> 
> It's because the project already has `react` and `react-dom` declared in its [main package.json](https://github.com/nikkilr88/ui-blocks/blob/master/package.json#L26-L27)
> 
> Easy enough to fix, `react` and `react-dom` would need to be listed as `peer-dependencies` instead. I attached a screenshot below to show how the `example/package.json` file should be changed.
> 
> Not sure if @nikkilr88 would want a PR for the change, or if it it could be squeezed in as part of #2
> 
> ![image](https://user-images.githubusercontent.com/5106417/77240783-eac22280-6bb7-11ea-983d-45a7d8a79ff0.png)
> 
> ps) super nice library btw 💯

Hey! That's exactly it!

And thank you so much! I appreciate it! I kind of put this project on the back burner, but I want to get back to working on it.

**Comment by mtliendo** [comment]
yea, component libraries can get crazy, fast! Happy to help 😄

**Comment by nikkilr88** [comment]
> yea, component libraries can get crazy, fast! Happy to help 😄

Oh, thank you! That would be great! 🎊

**Comment by Ansontheprogrammer** [comment]
Thanks. Issue resolved!
